application: codequoter
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  upload: static/index.html
  static_files: static/index.html

- url: /success
  upload: static/success.html
  static_files: static/success.html

- url: /error
  upload: static/error.html
  static_files: static/error.html

- url: /enter
  script: enter.py

- url: /shuffle
  script: shuffle.py
  login: admin
